ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),
    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),

    path('ad/<int:pk>/favorite',views.AddFavoriteView.as_view(), name='ad_favorite'),

    path('ad/<int:pk>/unfavorite',views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/4.2/topics/http/urls/
app_name = 'autos'

urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.MakeView.as_view(), name='make_list'),
    path('lookup/create/', views.MakeCreate.as_view(), name='make_create'),
    path('lookup/<int:pk>/update/', views.MakeUpdate.as_view(), name='make_update'),
    path('lookup/<int:pk>/delete/', views.MakeDelete.as_view(), name='make_delete'),
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='all'),
    path('accounts/signup', views.sign_up, name='signup'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('ads.urls')),
    path('admin/', admin.site.urls), 
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^oauth/', include('social_django.urls', namespace='social')),
    path('home/', include('home.urls')),
    path('autos/', include('autos.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    re_path(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/4.2/ref/urls/#include

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.views import View
from django.conf import settings
from django.contrib.auth.models import User, auth
from django.shortcuts import redirect, render

# Create your views here.

# This is a little complex because we need to detect when we are
# running in various configurations


class HomeView(View):
    def get(self, request):
        host = request.get_host()
        islocal = host.find('localhost') >= 0 or host.find('127.0.0.1') >= 0
        context = {
            'installed': settings.INSTALLED_APPS,
            'islocal': islocal
        }
        return render(request, 'home/main.html', context)


def sign_up(request):
    if request.method == 'POST':
        user = request.POST['username']
        mail = request.POST['email']
        pas = request.POST['password']
        pas2 = request.POST['password2']

        if user and mail and pas:
            if pas == pas2:
               if User.objects.filter(email=mail).exists():
                  ctx = {'error_email' : 'This email used by another user'}
                  return render(request, 'registration/signup.htm', ctx)

               elif User.objects.filter(username=user).exists():
                  ctx = {'error_username' : 'This username used by another user'}
                  return render(request, 'registration/signup.htm', ctx)

               else:
                  usr = User.objects.create_user(username=user, email=mail, password=pas)
                  usr.save()
                  user_login = auth.authenticate(username=user, password=pas)
                  auth.login(request, user_login)
                  return redirect(request.GET['next'])

            else:
              ctx = {'error_password' : 'Passwords doesn,t match'}
              return render(request, 'registration/signup.htm', ctx)
        else:
           ctx = {"error_form" : 'All fields are required'}
           return render(request, 'registration/signup.htm', ctx)
    
    elif request.method == 'GET':
        return render(request, 'registration/signup.htm', {})

home/templates/home/main.html
{% extends "base_bootstrap.html" %} {% block content %}

<style>
  .container {
    height: 100vh;
    display: flex;
    justify-content: center;
  }

  .welcome {
    display: flex;
    align-items: center;
    gap: 25px;
  }

  .welcome ul li {
    background-color: #00ba7c;
    padding: 10px;
    border-radius: 15px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }
  .welcome ul li a {
    color: #fff;
    transition: 0.5s;
    font-weight: bold;
    position: relative;
  }
  .welcome ul li a::before {
    content: "";
    position: absolute;
    bottom: -4px;
    left: 0px;
    height: 3px;
    width: 0%;
    background: #16212c;
    transition: 0.5s;
  }
  .welcome ul li a:hover::before {
    width: 100%;
  }
  .welcome ul li p {
    position: relative;
    font-size: 14px;
    cursor: pointer;
    margin-top: 15px;
    transition: 0.5s;
    color: #fff;
    font-weight: bold;
  }
  .welcome ul li p::before {
    content: "";
    position: absolute;
    bottom: -4px;
    left: 0px;
    height: 3px;
    width: 0;
    background: #16212c;
    transition: 0.5s;
  }
  .welcome ul li p:hover::before {
    width: 100%;
  }
  .welcome-header {
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .welcome-header h1 {
    font-size: 5.5vh;
    color: #fff;
  }
  .welcome-header p {
    font-size: 18px;
    color: #09b863;
    font-weight: bold;
  }
  .des {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    background-color: #fff;
    z-index: 10;
    width: 400px;
    padding: 15px;
  }
  .des p {
    font-size: 20px;
  }
  .ov {
    display: none;
    content: "";
    position: absolute;
    height: 100%;
    width: 100%;
    left: 0;
    top: 0;
    background-color: #00000078;
    z-index: 2;
  }
  .toggle{
    display: block;
  }
</style>
<div class="ov ads">
  <div class="des">
    <h2>Ads App</h2>
    <p>
      In this app you can add an ad and you can view it and put it in favorite,
      and also you can make comments in ad and any user can see your comments .
    </p>
    <p>Try to login in this app and use the features of it.</p>
  </div>
</div>
<div class="ov auto">
  <div class="des">
    <h2>Auto App</h2>
    <p>
      In this app you can add the name of the company and add the name of products of this company
    </p>
    <p>Try to login in this app and use the features of it.</p>
  </div>
</div>
<section class="welcome">
  <ul>
    <li>
      <a href="{% url 'ads:all'%}">Go to Ads app</a>
      <p class="d-ad">Description</p>
    </li>
  </ul>
  <div class="welcome-header">
    <h1>Welcome to CRUD Web App</h1>
    <p>You can click and use all apps you can see</p>
  </div>
  <ul>
    <li>
      <a href="{% url 'autos:all'%}">Go to Auto app</a>
      <p class="d-at">Description</p>
    </li>
  </ul>
</section>
<script>
  document.querySelector('.d-ad').addEventListener('click', () => document.querySelector('.ads').classList.add('toggle'))
  document.querySelector('.ads').addEventListener('click', () => document.querySelector('.ads').classList.remove('toggle'))
  document.querySelector('.d-at').addEventListener('click', () => document.querySelector('.auto').classList.add('toggle'))
  document.querySelector('.auto').addEventListener('click', () => document.querySelector('.auto').classList.remove('toggle'))
</script>
{% endblock content %}